//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean @__actions_TeleRikshaw_in_ResetHandlebar;
        
        public static SteamVR_Action_Single @__actions_TeleRikshaw_in_Accelerate;
        
        public static SteamVR_Action_Single @__actions_TeleRikshaw_in_Brake;
        
        public static SteamVR_Action_Boolean @__actions_TeleRikshaw_in_Honk;
        
        public static SteamVR_Action_Boolean @__actions_TeleRikshaw_in_Music;
        
        public static SteamVR_Action_Pose @__actions_TeleRikshaw_in_LeftPose;
        
        public static SteamVR_Action_Pose @__actions_TeleRikshaw_in_RightPose;
        
        public static SteamVR_Action_Boolean @__actions_TeleRikshaw_in_ResetScenePosition;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_Brake.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_Honk.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_Music.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_LeftPose.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_RightPose.Initialize();
            SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_ResetHandlebar")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_Accelerate")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Brake = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_Brake")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Honk = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_Honk")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Music = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_Music")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_LeftPose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_LeftPose")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_RightPose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_RightPose")));
            Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_TeleRikshaw_in_ResetScenePosition")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Honk,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Music,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_LeftPose,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_RightPose,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Honk,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Music,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_LeftPose,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_RightPose,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_LeftPose,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_RightPose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Honk,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Music,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Brake};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetHandlebar,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Accelerate,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Honk,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_Music,
                    Valve.VR.SteamVR_Input.@__actions_TeleRikshaw_in_ResetScenePosition};
        }
    }
}
