//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TeleRikshaw_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean ResetHandlebar;
        
        public Valve.VR.SteamVR_Action_Single Accelerate;
        
        public Valve.VR.SteamVR_Action_Single Brake;
        
        public Valve.VR.SteamVR_Action_Boolean Honk;
        
        public Valve.VR.SteamVR_Action_Boolean Music;
        
        public Valve.VR.SteamVR_Action_Pose LeftPose;
        
        public Valve.VR.SteamVR_Action_Pose RightPose;
        
        public Valve.VR.SteamVR_Action_Boolean ResetScenePosition;
    }
}
